### ISSUE TITLE
New Owner / Project Maintainer Requested

### ISSUE THREAD

**Issue by farvour** [macstadium/packer-plugin-macstadium-orka#12]
Reaching out here to the stakeholders of the Orka project at MacStadium. Since we are no longer leveraging the Orka services at MacStadium, maintenance of this project will be difficult. I'm proactively filing this Issue hoping this repository can have its ownership transferred to some sort of official MacStadium GitHub capacity? Can also add any stakeholders of this project who are actively using it as authorized contributors for the time being.

@jpraczyk

**Comment by jpraczyk** [comment]
I've asked macstadium whether they would be interested in taking ownership of this project here https://ideas.macstadium.com/ideas/ORKA-I-44

**Comment by chapmanorka** [comment]
Hi! I'm the Chief Product Officer at MacStadium.  Our product team  is working this week to take the maintainer responsibility. We're sorry to see you go from Orka but appreciate all the work on this project that you've provided.  The Orka community definitely values the contribution.  We've talked with the dev and product team to get the ball rolling on this today.  Thanks for reaching out.

**Comment by farvour** [comment]
Thanks @chapmanorka ! I have been working with the MacStadium team to get the transfer initiated.
